Typescript Implementation of Commit Synchronization
google/gink pull request #9
Opened 2022-02-22 17:25 UTC by darinmcgill

Proto definitions needed for the version 1 synchronization protocol.  

PR not completely ready for review yet: need to pull out the non-sync related protos into another branch, and want to rename "Transaction" to "Commit" to align more closely with Git and avoid confusion with transactions in underlying data store.

2022-07-15 04:28 UTC, ShubhamAvasthi submitted a review, later dismissed

2022-07-15 04:28 UTC, ShubhamAvasthi commented on proto/messages.proto
> +
Extra space at the top of the file should be removed.

2022-07-15 04:28 UTC, ShubhamAvasthi commented on proto/transactions.proto
> +*/
Comments should follow the style mentioned in https://developers.google.com/protocol-buffers/docs/proto#adding_comments.

2022-07-17 23:54 UTC, darinmcgill commented on proto/transactions.proto
> +*/
What you pointed to isn't a style guide it's merely examples showing that proto files support C/C++ style comments.

2022-07-17 23:57 UTC, darinmcgill commented on proto/messages.proto
> +
done

2022-08-29 23:06 UTC, dmgeels requested changes
I went through a couple key files with a fine-toothed comb. I haven't looked at every file yet.

2022-08-29 23:06 UTC, dmgeels commented on typescript/Instance.ts
> +            const waitNeeded = Date.now() * 1000 > lastTimestamp ? 0 : 1;
I: Oh, this is all local, with millisecond granularity? How about just pumping the timestamp up 1 microsecond?

2022-08-29 23:06 UTC, dmgeels commented on typescript/Instance.ts
> +        this.medallion = medallion;
I: Why does the medallion come late?

2022-08-29 23:06 UTC, dmgeels commented on typescript/Instance.ts
> +export class Obj { }
W: explain

2022-08-29 23:06 UTC, dmgeels commented on typescript/Instance.ts
> + * This Identifier class is intended to be used when you want
I: Where do you use this? And when does the real reference get filled in? I would have thought this would just be a CommitInfo with no timestamp.

2022-09-06 08:24 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +console.log(`mode=${mode}`);
Removing

2022-09-06 08:36 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +    constructor(indexedDbName = "default", reset = false) {
Going with "gink-default" in order to be explicit.

2022-09-06 08:42 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +        this.wrapped.close();
Good catch.

2022-09-06 08:45 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +        await this.initialized;
Yeah I think having them fail if initialization failed is the right behavior, but I agree that behavior should be documented somewhere.  I'm going to update the doc-strings in the Store interface.

2022-09-06 08:59 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +        for (let i = 0; i < items.length; i++) {
I can see it being slightly more efficient, but I think it'll be easier to debug by just dumping everything to an array if things get weird.

2022-09-06 09:08 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +    async getHasMap(): Promise<ChainTracker> {
Yeah I agree that it's better though I still think it isn't as descriptive as I'd like.  If you think of anything else let me know.

2022-09-06 09:29 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +            hasMap.markIfNovel(value)
I don't think it's possible with the current implementation for any instance to have chains with gaps.  (It's certainly not intended to allow that.)

2022-09-06 09:32 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +        let wrappedTransaction: IDBPTransaction = this.wrapped.transaction(['chainInfos']);
Yeah good point, I'm just going to take you inline suggestion.

2022-09-06 09:54 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +                return false;
Okay fixed the docstring in the interface (Store) to describe the intended behavior.  I don't think that the transaction needs to be explicitly closed if no writes occur within it but I've created an issue to track the question and have added an appropriate TODO comment.  https://github.com/google/gink/issues/27

2022-09-06 10:03 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +    // to the current commit, so its best if `callBack` doesn't await.
Yeah I agree that this is not ideal.  I chose this approach because the documentation for idb and IndexedDB have warnings about calling await in the middle of a transaction.  Might not be as much a problem for read-only transactions?  Should probably be revisited at some point so I've created an issue to track: https://github.com/google/gink/issues/28

2022-09-06 10:10 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +        await wrappedTransaction.objectStore('activeChains').add({ chainStart, medallion });
In version 1 there won't be any medallion reuse/transfer, so it's not something worth stressing about right now, but it'll be a core issue in version 2, so I've created an issue to track this: https://github.com/google/gink/issues/29

2022-09-06 10:24 UTC, darinmcgill commented on typescript/Expector.js
> +    notify(fragment) {
Okay just added some.

2022-09-06 10:32 UTC, darinmcgill commented on typescript/Instance.ts
> +var W3cWebSocket = typeof WebSocket == 'function' ? WebSocket :
This is a good idea, though I think there's some subtly here because I'm using the conditional inclusion/tree shaking from Web Pack to avoid pulling in things like the Server code, and I want to avoid making that too complicated.  I've created an issue to track: https://github.com/google/gink/issues/31

2022-09-06 10:44 UTC, darinmcgill commented on typescript/Instance.ts
> +export class Instance {
Yeah Instance is ambiguous.  Switched to GinkInstance.

2022-09-10 07:48 UTC, darinmcgill commented on typescript/Instance.ts
> +    addListener(listener: CommitListener) {
yeup added

2022-09-10 07:50 UTC, darinmcgill commented on typescript/Instance.ts
> +        if (this.availableChains.size == 0) {
I've changed the implementation so that each GinkInstance only writes to a single chain.  I don't think it's worth the trouble to juggle multiple chains within an instance (though there's still reason for the store to own multiple chains, such as if two browser windows are opened, though I haven't worked out that case yet)

2022-09-10 07:51 UTC, darinmcgill commented on typescript/Instance.ts
> +        for (const [_peerId, peer] of this.peers) {
well yeah that's better.  fixed.

2022-09-10 07:55 UTC, darinmcgill commented on typescript/Instance.ts
> +            await listener(commitInfo);
At the moment I'm not expecting multiple commit listeners that would take a long time and is primarily so the users of the instance can update user interface elements.  I'm somewhat unsure if this should be an async call at all.  In any case at the moment my inclination is to keep it somewhat simple.

2022-09-10 08:11 UTC, darinmcgill commented on typescript/Instance.ts
> +                // TODO: chain these receiveCommit class to ensure they get processed
Making use of the new PromiseChainLock class to ensure that we're not doing more than one thing at a time.

2022-09-10 08:17 UTC, darinmcgill commented on typescript/Instance.ts
> +                // TODO: figure out how to block processing of receiving other messages while sending
Well we need to keep track of how much each chain each peer has (and yeah I know that's like n-squared on number of instances).

2022-09-10 08:18 UTC, darinmcgill commented on typescript/Instance.ts
> +            const waitNeeded = Date.now() * 1000 > lastTimestamp ? 0 : 1;
Yeah switched to that.  (Initially considered that approach but rejected it in favor of doing something stupid which I've since removed).

2022-09-10 08:24 UTC, darinmcgill commented on typescript/Instance.ts
> +                console.error(`error on connection ${connectionId} to ${target}, ${ev}`)
done.

2022-09-10 08:32 UTC, darinmcgill commented on typescript/Instance.ts
> +        this.medallion = medallion;
Okay I've changed the implementation somewhat since then, but basically we don't want to associate the commit with a particular medallion or timestamp until it comes time to add that pending commit to the system.  This will make things a bit weird when it comes to addressing objects that haven't been committed yet.

I'm contemplating binding the medallion at the creation of the PendingCommit, right now I'm letting whatever's sealing the system decide that, so in cases where we have multiple medallions in play we don't have to prematurely assume that we're using any particular one.

2022-09-10 08:35 UTC, darinmcgill commented on typescript/Instance.ts
> +export class Obj { }
I've moved this to be an interface in the typedefs file and put a doc string on it.

2022-09-10 08:37 UTC, darinmcgill commented on typescript/Instance.ts
> + * This Identifier class is intended to be used when you want
I'm setting things up so that which chain a commit lands on doesn't have to be decided until it's actually added (though I might revisit this).

2022-09-19 23:27 UTC, dmgeels approved these changes
I took one last pass through most of the files (skipped tests). 
This is definitely good to go. Let's merge it in and start with the next chunk so I can get caught up!

2022-09-19 23:27 UTC, dmgeels commented on typescript/GinkInstance.ts
> +    static readonly PROTOCOL = "gink";
I: This feels like an odd place to define global constants. How about a public constants file?

2022-09-19 23:27 UTC, dmgeels commented on typescript/IndexedDbStore.ts
> +    async addCommit(commitBytes: CommitBytes, commitInfo: CommitInfo): Promise<Boolean> {
I: Can you add docs to the remaining functions? What does the return value mean here?

2022-09-19 23:27 UTC, dmgeels commented on typescript/PromiseChainLock.ts
> +     *   unlockingFunction();
E: This example is bad if the try block throws.

2022-09-19 23:47 UTC, darinmcgill commented on typescript/ChainTracker.ts
> +            for (const [chainStart, commitInfo] of medallionMap) {
Well depends on what you mean by many.  The initial release of gink will target within enterprise use cases where everyone is using randomly selected medallions and only needs to verify that a given medallion hasn't been reused within the org.  In the future though we'll be using medallions somewhat like IP addresses and so expect a new chain to be started every time it's reassigned.  So not a lot but to future proof the system it makes sense to be ready for a lot of starts.

2022-09-19 23:57 UTC, darinmcgill commented on typescript/CommandLineInterace.ts
> +export class CommandLineInterface {
Well I'd expect it to evolve until I think of something better.
Added an issue: https://github.com/google/gink/issues/43 to track adding --help

2022-09-20 00:00 UTC, darinmcgill commented on typescript/GinkInstance.ts
> +    static readonly PROTOCOL = "gink";
Yeah I put it there because only the GinkInstance class and it's decedents will use it.  I'll start a constants file if I end up with more than a few constants.

2022-09-20 00:09 UTC, darinmcgill commented on typescript/IndexedDbStore.ts
> +    async addCommit(commitBytes: CommitBytes, commitInfo: CommitInfo): Promise<Boolean> {
So generally I am not documenting usage when I'm implementing interface methods, instead documenting them in the interface.  What you have reminded me is that I need to add the override keyword to all of these and then disable implicit overrides.

2022-09-20 08:17 UTC, darinmcgill commented on typescript/ChainTracker.ts
> +        assert(commitInfo.timestamp == commitInfo.chainStart || commitInfo.priorTime);
Switched this to explicitly throwing an error.  I think raising an exception is the right thing to do because it will cause the disconnect of the peer (and we probably don't want to be getting any more data if they're not sending us well formed commits).

2022-09-20 08:22 UTC, darinmcgill commented on typescript/PromiseChainLock.ts
> +     *   unlockingFunction();
Yeah good catch, updated it.

2022-09-20 08:30 UTC, merged